// Package notices carries the third-party licence text compiled into the
// binary.
//
// The content of THIRD-PARTY-NOTICES.txt is generated by `make notices`, which
// runs go-licenses over the real module graph. It is committed rather than
// produced at build time because `go build` and `go install` must work from a
// plain checkout with no extra tooling — and because go:embed requires the file
// to exist in the source tree at compile time.
//
// Keeping it in its own package rather than in cmd/ means `go build` fails
// loudly if the file is ever deleted, instead of silently producing a binary
// that ships no attribution.
package notices

import (
	_ "embed"
	"strings"
)

//go:embed THIRD-PARTY-NOTICES.txt
var embedded string

// placeholderMarker appears in the committed stub and is removed by the
// generator. Its presence means a real inventory was never generated for this
// build, which the `licenses` command reports rather than printing an empty
// document that reads like "no dependencies".
const placeholderMarker = "NOTICES-NOT-GENERATED"

// Text returns the embedded third-party licence notices.
func Text() string {
	return embedded
}

// IsPlaceholder reports whether this binary was built without a generated
// inventory. Release builds must never return true; CI enforces that.
func IsPlaceholder() bool {
	return strings.Contains(embedded, placeholderMarker)
}
