#!/usr/bin/env bash
# =============================================================================
# Vendor the bench UI's frontend assets into internal/benchui/ui/vendor/
# =============================================================================
#
# The bench UI is compiled into the binary by `//go:embed ui/*`. It must make
# zero network requests at page load. Two independent reasons:
#
#   Air-gap   This is the point. `ai-studio-cli bench-ui` runs on GPU nodes,
#             which are routinely isolated, and serves the dashboard on
#             localhost. A Google Fonts <link> there is not a slow load — it is
#             a dashboard that renders in fallback fonts on the exact machines
#             this tool exists to benchmark. Embedding the UI in the binary and
#             then having it phone out for fonts defeats the embedding.
#
#   Privacy   Requesting fonts from fonts.googleapis.com discloses the
#             operator's IP to a third party. LG München I, 3 O 17493/20
#             (20 Jan 2022) held that to be a GDPR breach absent consent.
#
# Self-hosting the fonts creates an SIL OFL-1.1 obligation to ship the copyright
# and licence with them. Handled here: the LICENSE files are copied alongside
# the .woff2 files and summarised in vendor/NOTICE.
#
# WHY THESE BINARIES ARE COMMITTED
#
# Unlike aistudio-app, where the vendored assets are gitignored and fetched at
# setup time, these are committed. `go build` does not run npm, and `go:embed`
# requires the files to exist in the source tree at compile time. Anyone with a
# Go toolchain and a checkout must be able to produce a working binary. Making
# that depend on a prior npm run would break `go install`.
#
# Usage:
#   ./scripts/vendor-ui-assets.sh              # re-fetch and regenerate
#   VENDOR_DEST=/tmp/check ./scripts/...       # CI: regenerate elsewhere and diff
#
# Requires: npm
# =============================================================================

set -euo pipefail

# Exact versions. A floating major would ship different .woff2 bytes and fail
# CI's reproducibility diff on an unrelated PR.
INTER_VERSION="5.3.0"
JETBRAINS_VERSION="5.3.0"

# Must match the version the UI was written against. The previously vendored
# copy came from jsdelivr and was byte-identical to npm's dist/chart.umd.js for
# this version, plus a CDN banner.
CHARTJS_VERSION="4.4.7"

# Weights actually referenced by index.css (--font-sans, --font-mono).
# Every extra weight is ~25 KB compiled into the binary for nothing.
INTER_WEIGHTS=(400 500 600 700)
JETBRAINS_WEIGHTS=(400 500)

SUBSET="latin"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UI="$ROOT/ai-studio-cli/internal/benchui/ui"
DEST="${VENDOR_DEST:-$UI/vendor}"

if ! command -v npm >/dev/null 2>&1; then
  echo "ERROR: npm is required to vendor UI assets." >&2
  echo "       These files are committed, so this is only needed when updating them." >&2
  exit 1
fi

WORK="$(mktemp -d)"
BUILD="$WORK/stage"
trap 'rm -rf "$WORK"' EXIT

echo "Fetching packages ..."
cd "$WORK"
npm init -y >/dev/null 2>&1
npm install --no-audit --no-fund --silent \
  "@fontsource/inter@${INTER_VERSION}" \
  "@fontsource/jetbrains-mono@${JETBRAINS_VERSION}" \
  "chart.js@${CHARTJS_VERSION}"

MODULES="$WORK/node_modules"

# Stage then swap, so a failure partway through cannot leave the embedded UI
# half-populated — `go:embed` would then compile a broken dashboard into the
# binary with no error.
mkdir -p "$BUILD/fonts" "$BUILD/js"

echo "Copying fonts ..."
for w in "${INTER_WEIGHTS[@]}"; do
  cp "$MODULES/@fontsource/inter/files/inter-${SUBSET}-${w}-normal.woff2" "$BUILD/fonts/"
done
for w in "${JETBRAINS_WEIGHTS[@]}"; do
  cp "$MODULES/@fontsource/jetbrains-mono/files/jetbrains-mono-${SUBSET}-${w}-normal.woff2" "$BUILD/fonts/"
done

echo "Copying licences ..."
cp "$MODULES/@fontsource/inter/LICENSE"          "$BUILD/fonts/LICENSE-Inter-OFL.txt"
cp "$MODULES/@fontsource/jetbrains-mono/LICENSE" "$BUILD/fonts/LICENSE-JetBrainsMono-OFL.txt"
cp "$MODULES/chart.js/LICENSE.md"                "$BUILD/js/LICENSE-chartjs.md"

echo "Copying Chart.js ..."
# dist/chart.umd.js is already minified upstream; this is the same artifact the
# previous jsdelivr copy carried, minus the CDN banner.
cp "$MODULES/chart.js/dist/chart.umd.js" "$BUILD/js/chart.umd.js"

RANGE='U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'

echo "Generating fonts.css ..."
{
  echo "/* Self-hosted web fonts. Generated by scripts/vendor-ui-assets.sh — do not edit. */"
  echo "/* Inter — SIL OFL-1.1 — see fonts/LICENSE-Inter-OFL.txt */"
  for w in "${INTER_WEIGHTS[@]}"; do
    printf '@font-face{font-family:"Inter";font-style:normal;font-display:swap;font-weight:%s;src:url("./fonts/inter-%s-%s-normal.woff2") format("woff2");unicode-range:%s;}\n' \
      "$w" "$SUBSET" "$w" "$RANGE"
  done
  echo "/* JetBrains Mono — SIL OFL-1.1 — see fonts/LICENSE-JetBrainsMono-OFL.txt */"
  for w in "${JETBRAINS_WEIGHTS[@]}"; do
    printf '@font-face{font-family:"JetBrains Mono";font-style:normal;font-display:swap;font-weight:%s;src:url("./fonts/jetbrains-mono-%s-%s-normal.woff2") format("woff2");unicode-range:%s;}\n' \
      "$w" "$SUBSET" "$w" "$RANGE"
  done
} > "$BUILD/fonts.css"

echo "Writing NOTICE ..."
cat > "$BUILD/NOTICE" <<NOTICE
Third-party assets embedded in the ai-studio-cli bench UI
=========================================================

These files are compiled into the ai-studio-cli binary via //go:embed, so
their licence terms travel with every copy of the binary that is distributed.

Regenerate with: ./scripts/vendor-ui-assets.sh

Inter
  Copyright 2016 The Inter Project Authors (https://github.com/rsms/inter)
  SIL Open Font License 1.1 — fonts/LICENSE-Inter-OFL.txt
  Packaged via @fontsource/inter@${INTER_VERSION}

JetBrains Mono
  Copyright 2020 The JetBrains Mono Project Authors
  (https://github.com/JetBrains/JetBrainsMono)
  SIL Open Font License 1.1 — fonts/LICENSE-JetBrainsMono-OFL.txt
  Packaged via @fontsource/jetbrains-mono@${JETBRAINS_VERSION}

Chart.js ${CHARTJS_VERSION}
  Copyright (c) 2014-2024 Chart.js Contributors
  MIT — js/LICENSE-chartjs.md

OFL-1.1 note: these fonts are redistributed unmodified, under their original
names, and are not sold on their own, which is what OFL section 2 requires.
If a font file is ever subsetted or renamed, re-read sections 3 and 4.

MIT note: Chart.js previously lived here as a jsdelivr-fetched copy carrying
only a banner comment. A banner names the licence; it is not the licence. MIT
requires "the above copyright notice and this permission notice" to be included,
so the full text is now shipped in js/LICENSE-chartjs.md.
NOTICE

# ── Swap staged tree into place ──────────────────────────────────────────────
mkdir -p "$DEST"
rm -rf "$DEST/fonts" "$DEST/js"
mv "$BUILD/fonts" "$BUILD/js" "$DEST/"
mv "$BUILD/fonts.css" "$BUILD/NOTICE" "$DEST/"

echo
echo "Done. $(du -sh "$DEST" | cut -f1) in internal/benchui/ui/vendor/"
echo "These files are committed — 'go build' cannot fetch them."
